# Generated by Django 5.2.12 on 2026-03-27 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120)),
                ('image', models.ImageField(upload_to='place/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='JERM STUDIO', max_length=120)),
                ('hero_badge', models.CharField(default='Kids Photography Studio', max_length=120)),
                ('hero_title', models.CharField(default='JERM STUDIO', max_length=180)),
                ('hero_subtitle', models.CharField(default='Magical and cozy sets crafted for newborn, toddler, and children portraits.', max_length=300)),
                ('hero_button_text', models.CharField(default='Explore Rooms', max_length=80)),
                ('hero_background', models.ImageField(blank=True, null=True, upload_to='site/hero/')),
                ('rooms_title', models.CharField(default='Kids Studio Rooms', max_length=120)),
                ('rooms_subtitle', models.CharField(default='Soft textures, playful props, and gentle tones designed for children-focused storytelling.', max_length=300)),
                ('rooms_empty_title', models.CharField(default='Rooms Coming Soon', max_length=120)),
                ('rooms_empty_text', models.CharField(default='Add rooms in the admin panel to display them here.', max_length=220)),
                ('room_price_prefix', models.CharField(default='From', max_length=40)),
                ('room_custom_pricing_text', models.CharField(default='Custom pricing', max_length=80)),
                ('room_book_button_text', models.CharField(default='Book Now', max_length=80)),
                ('place_title', models.CharField(default='Place', max_length=120)),
                ('place_subtitle', models.CharField(default='Photos from our real studio sessions.', max_length=240)),
                ('booking_modal_title', models.CharField(default='Book a Session', max_length=120)),
                ('selected_room_prefix', models.CharField(default='Selected room', max_length=80)),
                ('booking_step_1', models.CharField(default='1. Date', max_length=80)),
                ('booking_step_2', models.CharField(default='2. Time', max_length=80)),
                ('booking_step_3', models.CharField(default='3. Details', max_length=80)),
                ('booking_choose_date_title', models.CharField(default='Choose a Date', max_length=80)),
                ('booking_choose_date_text', models.CharField(default='Only available dates are selectable.', max_length=180)),
                ('booking_choose_time_title', models.CharField(default='Choose a Time', max_length=80)),
                ('booking_choose_time_text', models.CharField(default='Time slots are shared globally across all rooms.', max_length=200)),
                ('booking_details_title', models.CharField(default='Your Details', max_length=80)),
                ('booking_submit_text', models.CharField(default='Confirm Booking', max_length=80)),
                ('first_name_placeholder', models.CharField(default='First Name', max_length=60)),
                ('last_name_placeholder', models.CharField(default='Last Name', max_length=60)),
                ('email_placeholder', models.CharField(default='Email', max_length=60)),
                ('phone_placeholder', models.CharField(default='Phone Number', max_length=60)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Content',
                'verbose_name_plural': 'Site Content',
            },
        ),
    ]
