# Generated by Django 5.2.12 on 2026-03-27 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_placephoto_sitecontent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitecontent',
            options={'ordering': ('language',), 'verbose_name': 'Site Content', 'verbose_name_plural': 'Site Content'},
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('hy', 'Armenian'), ('ru', 'Russian')], default='en', max_length=5, unique=True),
        ),
    ]
