# Generated by Django 5.2.12 on 2026-03-27 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_sitecontent_options_sitecontent_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='booking_error_text',
            field=models.CharField(default='Unable to create booking. Please try again.', max_length=160),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='booking_success_text',
            field=models.CharField(default='Booking confirmed.', max_length=120),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='loading_dates_text',
            field=models.CharField(default='Loading available dates...', max_length=120),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='loading_slots_text',
            field=models.CharField(default='Loading available slots...', max_length=120),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='no_slots_text',
            field=models.CharField(default='No slots available for this date. Please choose another day.', max_length=180),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='select_date_time_text',
            field=models.CharField(default='Please choose a date and time first.', max_length=140),
        ),
    ]
