# Generated by Django 5.2.12 on 2026-03-28 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_studio_logo_badge_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='studio_logo_image',
            field=models.ImageField(blank=True, help_text='PNG/SVG-style logo shown above the main title. Upload per language if designs differ.', null=True, upload_to='site/logo/', verbose_name='Studio logo (image)'),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='hero_badge',
            field=models.CharField(default='KIDS PHOTOGRAPHY STUDIO', help_text='Used as the image alt attribute for accessibility. If no logo image is uploaded, this text is shown in the styled pill instead.', max_length=160, verbose_name='Logo alt text & text fallback'),
        ),
    ]
