# Generated by Django 5.2.12 on 2026-04-01 08:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('booked', 'Booked'), ('canceled', 'Canceled')], default='booked', max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (7–15 digits, optional + prefix).', regex='^\\+?\\d{7,15}$')]),
        ),
    ]
