# Generated by Django 5.2.12 on 2026-03-28 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_seed_sitecontent_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecontent',
            name='hero_badge',
            field=models.CharField(default='KIDS PHOTOGRAPHY STUDIO', help_text='Uppercase tagline in the cream pill above the main title. Set per language (EN / HY / RU).', max_length=160, verbose_name='Studio logo (pill badge)'),
        ),
    ]
